SELECT * FROM TES_ALUNOCONTRATO
INNER JOIN ACD_ENTURMACAOVINCULO ENV ON ENV.CODIGOENTURMACAOVINCULO = TES_ALUNOCONTRATO.CODIGOENTURMACAOVINCULO
INNER JOIN ACD_ENTURMACAO ENT ON ENT.CODIGOENTURMACAO = ENV.CODIGOENTURMACAO
INNER JOIN TES_PLANOPAGAMENTO PAG ON PAG.CODIGOPLANOPAGAMENTO = TES_ALUNOCONTRATO.CODIGOPLANOPAGAMENTO
INNER JOIN ACD_TURMA TUR ON TUR.CODIGOTURMA = ENT.CODIGOTURMA
